### ISSUE TITLE
Menambahkan konten file HTML

### ISSUE THREAD

**Issue by lunchboxav** [lunchboxav/git-practice#1]
Untuk permulaan, kita butuh 1 file HTML, untuk dioprek bersama

**Comment by arsaizdihar** [comment]
Saya tertarik kak

**Comment by kevindoubleu** [comment]
saya bingung kak kalo ada issue gini, bagusnya comment dulu apa lgsg submit pull req aja ya?

**Comment by lunchboxav** [comment]
close via #5
